[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Fake Shopping API"
description = "A fake shopping API for testing purposes"
version = "0.0.1"
dependencies = [
    "fastapi[all]",
    "sqlmodel",
]